import CriticalGK2.SparseMatrixNil

/-!
# Two actual generators of the positive all-cut quotient

The generators are the images of the two literal one-letter words.  Every
nonempty word is a product of those letters.  The zero augmentation condition
removes the empty word from the finite coefficient expansion.  Passing through
the actual inclusion A -> B = H/E proves that the non-unital subalgebra
generated by these two elements is all of A.

This result needs only the already proved actual quotient and positive-part
surjection. The final theorem applies to the same constructed
`OriginalFieldNilAlgebra` as the matrix-nil endpoint.
-/

namespace CriticalGK2.Actual

noncomputable section

open scoped BigOperators

variable (F : Type*) [Field F]

/-- The actual image in A of one of the two original letters. -/
def positiveGenerator (W : DyadicDualData F) (hW : PrimalCoherent F W)
    (b : Bool) : PositiveAllCutQuotient F W hW :=
  positiveAllCutQuotientMap F W hW
    ⟨MonoidAlgebra.single (FreeMonoid.of b) 1, augmentation_letter F b⟩

@[simp]
theorem positiveGenerator_val (W : DyadicDualData F) (hW : PrimalCoherent F W)
    (b : Bool) : (positiveGenerator F W hW b).val =
      allCutQuotientMap F W hW (MonoidAlgebra.single (FreeMonoid.of b) 1) := rfl

/-- Every nonempty word image belongs to every non-unital subalgebra of B
containing the two actual letter images. -/
theorem quotient_monomial_mem_of_letters_mem (W : DyadicDualData F)
    (hW : PrimalCoherent F W)
    (S : NonUnitalSubalgebra F (AllCutRingQuotient F W hW))
    (hletters : ∀ b : Bool,
      allCutQuotientMap F W hW (MonoidAlgebra.single (FreeMonoid.of b) 1) ∈ S)
    (w : Word) : w ≠ 1 →
      allCutQuotientMap F W hW (MonoidAlgebra.single w 1) ∈ S := by
  refine FreeMonoid.recOn w ?_ ?_
  · intro hw
    exact False.elim (hw rfl)
  · intro b w ih _
    by_cases hw : w = 1
    · subst w
      simpa only [mul_one] using hletters b
    · have hm := S.mul_mem (hletters b) (ih hw)
      have hq : allCutQuotientMap F W hW
          (MonoidAlgebra.single (FreeMonoid.of b) (1 : F) * MonoidAlgebra.single w 1) =
          allCutQuotientMap F W hW (MonoidAlgebra.single (FreeMonoid.of b) 1) *
            allCutQuotientMap F W hW (MonoidAlgebra.single w 1) :=
        map_mul (allCutQuotientMap F W hW) _ _
      have heq : allCutQuotientMap F W hW
          (MonoidAlgebra.single (FreeMonoid.of b * w) (1 : F)) =
          allCutQuotientMap F W hW (MonoidAlgebra.single (FreeMonoid.of b) 1) *
            allCutQuotientMap F W hW (MonoidAlgebra.single w 1) := by
        simpa only [MonoidAlgebra.single_mul_single, one_mul] using hq
      rw [heq]
      exact hm

/-- The finite word expansion of an element of H+ uses only nonempty words,
so its actual image lies in the same subalgebra. -/
theorem quotient_positive_mem_of_letters_mem (W : DyadicDualData F)
    (hW : PrimalCoherent F W)
    (S : NonUnitalSubalgebra F (AllCutRingQuotient F W hW))
    (hletters : ∀ b : Bool,
      allCutQuotientMap F W hW (MonoidAlgebra.single (FreeMonoid.of b) 1) ∈ S)
    (x : WordAlgebra F) (hx : augmentation F x = 0) :
    allCutQuotientMap F W hW x ∈ S := by
  classical
  have hxempty : x 1 = 0 := by
    rw [← augmentation_eq_constantCoeff F x]
    exact hx
  rw [MonoidAlgebra.lift_unique (allCutQuotientMap F W hW) x]
  change (∑ w ∈ x.support, x w •
    allCutQuotientMap F W hW (MonoidAlgebra.single w 1)) ∈ S
  apply S.toSubmodule.sum_mem
  intro w hw
  apply S.smul_mem
  apply quotient_monomial_mem_of_letters_mem F W hW S hletters w
  intro he
  subst w
  exact (Finsupp.mem_support_iff.mp hw) hxempty

/-- Any non-unital subalgebra of A containing the two actual generators is
the whole actual positive quotient. -/
theorem positiveSubalgebra_eq_top_of_generators_mem (W : DyadicDualData F)
    (hW : PrimalCoherent F W)
    (S : NonUnitalSubalgebra F (PositiveAllCutQuotient F W hW))
    (hletters : ∀ b : Bool, positiveGenerator F W hW b ∈ S) : S = ⊤ := by
  apply eq_top_iff.mpr
  intro a _
  let T : NonUnitalSubalgebra F (AllCutRingQuotient F W hW) :=
    S.map (positiveQuotientInclusion F W hW)
  have hTletters : ∀ b : Bool,
      allCutQuotientMap F W hW (MonoidAlgebra.single (FreeMonoid.of b) 1) ∈ T := by
    intro b
    exact NonUnitalSubalgebra.mem_map.mpr
      ⟨positiveGenerator F W hW b, hletters b, rfl⟩
  obtain ⟨x, hx⟩ := positiveAllCutQuotientMap_surjective F W hW a
  have hxT : allCutQuotientMap F W hW x.val ∈ T :=
    quotient_positive_mem_of_letters_mem F W hW T hTletters x.val x.property
  obtain ⟨a', ha', he⟩ := NonUnitalSubalgebra.mem_map.mp hxT
  have hae : a' = a := by
    apply Subtype.ext
    change a'.val = a.val
    calc
      a'.val = allCutQuotientMap F W hW x.val := he
      _ = a.val := congrArg (fun y : PositiveAllCutQuotient F W hW => y.val) hx
  exact hae ▸ ha'

/-- The actual positive quotient is generated by the two original letters,
in Mathlib's standard non-unital adjoin sense. -/
theorem positiveAllCutQuotient_two_generated (W : DyadicDualData F)
    (hW : PrimalCoherent F W) :
    NonUnitalAlgebra.adjoin F (Set.range (positiveGenerator F W hW)) = ⊤ := by
  apply positiveSubalgebra_eq_top_of_generators_mem F W hW
  intro b
  exact NonUnitalAlgebra.subset_adjoin F ⟨b, rfl⟩

/-- A literal pair formulation of the same generation statement. -/
theorem positiveAllCutQuotient_pair_generated (W : DyadicDualData F)
    (hW : PrimalCoherent F W) :
    NonUnitalAlgebra.adjoin F
      ({positiveGenerator F W hW false, positiveGenerator F W hW true} :
        Set (PositiveAllCutQuotient F W hW)) = ⊤ := by
  apply positiveSubalgebra_eq_top_of_generators_mem F W hW
  intro b
  apply NonUnitalAlgebra.subset_adjoin F
  cases b <;> simp

/-- The two specified generators of the actual constructed algebra Q_F. -/
def originalFieldGenerator (b : Bool) : OriginalFieldNilAlgebra F :=
  positiveGenerator F
    (sparseDualData F (fun n : ℕ => (n : ℝ)) linearEnvelope_diverges)
    (sparseDualData_primalCoherent F (fun n : ℕ => (n : ℝ)) linearEnvelope_diverges) b

/-- Two generation is proved for the same actual Q_F appearing in the
original-field and scalar-extension matrix-nil theorems. -/
theorem originalField_two_generated :
    NonUnitalAlgebra.adjoin F (Set.range (originalFieldGenerator F)) = ⊤ :=
  positiveAllCutQuotient_two_generated F _ _

#print axioms CriticalGK2.Actual.positiveAllCutQuotient_two_generated
#print axioms CriticalGK2.Actual.positiveAllCutQuotient_pair_generated
#print axioms CriticalGK2.Actual.originalField_two_generated

end

end CriticalGK2.Actual
